# For a comprehensive sample file, go to:
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
#
# Enable Access logs.
accessLog:
  filters:
    statusCodes:
      - "200"
      - "400-599"
    # Keep the access logs when at least one retry has happened.
    retryAttempts: true
    # Keep access logs when requests take longer than the specified duration.
    minDuration: "10ms"
#
additionalArguments:
  # For a list of static configuration, go to:
  # https://doc.traefik.io/traefik/reference/static-configuration/cli/
  #
  # Prometheus metrics exporter type.
  # - "--metrics.prometheus=true"
  # Match the path to persistence.
  - "--certificatesresolvers.le.acme.storage=/traefik-certs/acme.json"
# Enable api.
# For a list of API enpoints, go to https://doc.traefik.io/traefik/operations/api/#endpoints.
api:
  # Activate dashboard.
  # With Dashboard enabled, the router rule must catch requests for both /api and /dashboard.
  dashboard: true
  insecure: false
#
certificatesResolvers:
  # Let's Encrypt.
  le:
    # Enable ACME.
    acme:
      # email address used for registration.
      email: 'juancarlos@trimino.com'
      # CA server to use; the default is staging.
      # The staging environment will not issue trusted certificates but is used to ensure that the
      # verification process is working properly before moving to production. Let's Encrypt's
      # production environment imposes much stricter rate limits
      # (https://letsencrypt.org/docs/rate-limits/), so to reduce the chance of you hitting those
      # limits it is highly recommended to start by using the staging environment. To move to
      # production, simply create a new Issuer with the URL set to
      # https://acme-v02.api.letsencrypt.org/directory.
      # Production.
      # caServer: https://acme-v02.api.letsencrypt.org/directory
      # Staging.
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # Certificates' duration in hours.
      # Let's Encrypt certificates' duration defaults to 2160 hours (90 days).
      certificatesDuration: 720  # 30 days.
      # Preferred chain to use.
      # If the CA offers multiple certificate chains, prefer the chain with an issuer matching this
      # Subject Common Name. If no match, the default offered chain will be used.
      preferredChain: 'ISRG Root X1'
      # KeyType to use.
      # Available values: "EC256", "EC384", "RSA2048", "RSA4096", "RSA8192"
      keyType: 'RSA4096'
      # Use the TLS-ALPN-01 challenge to generate and renew ACME certificates by provisioning a TLS
      # certificate. When using the TLS-ALPN-01 challenge, Traefik must be reachable by Let's
      # Encrypt through port 443.
      # tlsChallenge:
      # httpChallenge:
      # Use a DNS-01 ACME challenge rather than HTTP-01 challenge; enable a dns challenge named
      # "le".
      # Note: mandatory for wildcard certificate generation.
      dnsChallenge:
        # DNS provider used.
        # For supported providers, go to https://doc.traefik.io/traefik/https/acme/#providers.
        provider: digitalocean
        # By default, the provider will verify the TXT DNS challenge record before letting ACME
        # verify. If delayBeforeCheck is greater than zero, this check is delayed for the
        # configured duration in seconds. Useful if internal networks block external DNS queries.
        delayBeforeCheck: 0
        # Use the following DNS servers to resolve the FQDN authority:
        # Cloudflare -> 1.1.1.1,1.0.0.1
        # Google -> 8.8.8.8,8.8.4.4
        #
        # To check DNS propagation:
        # https://dnschecker.org/
        # https://www.whatsmydns.net/
        #
        # The Authoritative DNS servers store the most recent and accurate information (DNS
        # records) for a domain and are able to provide the final answers for users' DNS queries
        # (DNS lookups).
        # To get the Authoritative DNS servers for a domain:
        # $ dig +short NS trimino.xyz
        # $ nslookup -type=NS trimino.xyz
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'
          - '8.8.8.8:53'
          - '8.8.4.4:53'
      # Match the path to persistence.
      # storage: '/traefik-certs/acme.json'
deployment:
  enabled: true
  replicas: 1
  # initContainers:
  #   # The "volume-permissions" init container is required if you run into permission issues.
  #   # Related issue: https://github.com/containous/traefik/issues/6972
  #   - name: volume-permissions
  #     image: busybox:latest
  #     command: ["sh", "-c", "chmod -Rv 600 /traefik-certs/*"]
  #     volumeMounts:
  #       - name: traefik-certs
  #         mountPath: /traefik-certs
# For a list of annotations, go to
# https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#annotations
entryPoints:
  # Traefik will listen to incoming request on the port 80 (http).
  web:
    address: ':80'
    # Targeted entry point of the redirection.
    http:
      redirections:
        entrypoint:
          to: websecure
          # Scheme used for the redirection.
          scheme: https
          # Apply a permanent redirection.
          permanent: true
  # Traefik will listen to incoming request on the port 443 (https).
  websecure:
    address: ':443'
    http:
      # Default TLS configuration for the routers linked to the entry point.
      tls:
        # Default certificate resolver for the routers linked to the entry point.
        certResolver: le
# Environment variables to be passed to Traefik's binary.
env:
  - name: DO_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: mem-traefik-provider-secret
        key: api_auth_token
#
# Set Traefik as the default Ingress Controller (as per Kubernetes 1.19+ changes).
ingressClass:
  enabled: true
  isDefaultClass: true
# Create an IngressRoute for the dashboard.
ingressRoute:
  dashboard:
    # Using a custom ingressRoute with basic auth instead of the default.
    enabled: false
    # Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class).
    annotations: {}
    # Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels).
    labels: {}
# Liveness and readiness probes.
livenessProbe:
  httpGet:
    path: /ping
    port: 9000
    scheme: HTTP
  # How long to wait after the container starts before beginning the probe.
  initialDelaySeconds: 5
  # The frequency of the checks.
  periodSeconds: 10
  # How long to wait for the probe to finish. If this time is exceeded, then K8s assumes that the
  # probe failed.
  timeoutSeconds: 2
  # The minimum consecutive successes for the probe to be considered successful after it has
  # failed.
  successThreshold: 1
  # The minimum consecutive failures for the probe to be considered failed after it has succeeded.
  failureThreshold: 3
#
readinessProbe:
  httpGet:
    path: /ping
    port: 9000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 1
#
logs:
  access:
    enabled: true
    format: json
  general:
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL,
    # ERROR, WARN, and INFO.
    level: ERROR
# Enable Healthcheck.
ping: {}
# Persistent Storage.
persistence:
  enabled: true
  name: traefik-certs
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /traefik-certs
#
ports:
  metrics:
    port: 9100
    # See traefik below.
    expose: false
    # The exposed port for this service.
    exposedPort: 9100
  traefik:
    port: 9000
    # DO NOT expose the traefik port on production deployments. To access it from outside of the
    # cluster, use `kubectl port-forward` or create a secure ingress.
    # $ kubectl port-forward -n memories $(kubectl get pods -n memories --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000
    # From a browser, use http://127.0.0.1:9000/dashboard/ to see the Traefik dashboard; the trailing slash / in /dashboard/ is mandatory.
    expose: false
    # The exposed port for this service.
    exposedPort: 9000
  web:
    port: 80  # Traefik port.
    expose: true
    exposedPort: 80
    # (Optional) Permanent Redirect to HTTPS.
    redirectTo: websecure
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    tls:
      enabled: true
      # (Optional) Set a default certificate resolver.
      certResolver: digitalocean
# Prometheus Metrics.
# metrics:
#   prometheus:
#     # Prometheus metrics buckets have been enabled for the different time series in seconds.
#     buckets:
#       - 0.1
#       - 0.3
#       - 1.2
#       - 5.0
#       - 10.0
# Configure providers.
providers:
  # Enable Kubernetes backend with default settings.
  kubernetes.CRD:
    enabled: true
  # Enable Kubernetes backend with default settings.
  kubernetesIngress:
    enabled: true
    # Value of kubernetes.io/ingress.class annotation or IngressClass name to watch for. See
    # https://cert-manager.io/docs/installation/upgrading/ingress-class-compatibility/#traefik.
    ingressClass: traefik
# Whether Role Based Access Control objects like roles and rolebindings should be created.
rbac:
  enabled: true
  # If set to false, installs ClusterRole and ClusterRoleBinding so Traefik can be used across
  # namespaces.
  # If set to true, installs namespace-specific Role and RoleBinding and requires provider
  # configuration be set to that same namespace.
  namespaced: true
# QoS (Guaranteed).
resources:
  # requests:
  #   cpu: "500m"
  #   memory: "150Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
# Set the container security context.
# To run the container with ports below 1024 this will need to be adjust to run as root.
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
# The service account the pods will use to interact with the Kubernetes API.
serviceAccount:
  # If set, an existing service account is used.
  # If not set, a service account is created automatically using the fullname template.
  # name: ""
  name: "mem-traefik-service-account"
